version: '3'



services:
    cupmaze:
      build: .
      ports:
      - "8000:8000"
      depends_on:
      - mongodb
      environment:
      - MONGO_URI=mongodb://mongodb:27017/


    mongodb:
      image: mongo:latest
      container_name: mongo_container
      volumes:
        - mongodb_data:/data/db
        - ./mongod.conf:/etc/mongod.conf

volumes:
    mongodb_data: